# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/Ezzud/ironspells-hud/refs/heads/client-only/update.json"
modURL = "https://github.com/Ezzud/ironspells-hud/"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "assets/logo.png"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_spellbooks"
type = "required"
versionRange = "[1.0,)"
reason="You need this mod to fetch its Mana value"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "spiffyhud"
type = "optional"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "fancymenu"
type = "optional"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"
